/* Fetches Material Symbols (Apache-2.0, Google) and writes lib/icons/paths.ts.
 *
 * Run once, output committed -- the same pattern as the seed. Three reasons
 * not to load the icon font at runtime instead:
 *
 *   1. Material Symbols Outlined is a ~3.7 MB variable font covering ~3,000
 *      glyphs. This app uses about sixty. Inlining sixty paths costs ~14 KB.
 *   2. `font-src 'self'` in next.config.ts stays as it is. A Google Fonts
 *      stylesheet would need fonts.googleapis.com and fonts.gstatic.com added
 *      to the CSP, and a CSP mistake fails as an invisible blank icon.
 *   3. No build-time network call, so a Vercel deploy cannot fail because
 *      fonts.google.com was slow.
 *
 * Re-run with `npm run icons` after editing MANIFEST.
 */

import { writeFile } from 'node:fs/promises';

const SRC = (name: string) =>
  `https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/${name}/default/24px.svg`;

/* Every icon the app can draw. Grouped by why it exists, so an unused one is
 * visible rather than accumulating. */
const MANIFEST: string[] = [
  // tag-kind defaults
  'description', 'label', 'person', 'calendar_month', 'find_in_page',
  'bookmark', 'star', 'tag',
  // media types
  'image', 'movie', 'music_note', 'draft', 'category',
  // topics
  'payments', 'gavel', 'groups', 'engineering', 'campaign', 'trending_up',
  'science', 'medical_services', 'school', 'settings', 'shield', 'flight',
  'palette',
  // doctypes
  'receipt_long', 'receipt', 'account_balance', 'handshake', 'assessment',
  'slideshow', 'table_chart', 'terminal', 'code', 'badge', 'mail',
  'event_note', 'list_alt', 'article', 'menu_book', 'policy', 'lightbulb',
  'record_voice_over', 'screenshot', 'workspace_premium', 'photo_camera', 'mic',
  // patterns
  'paid', 'numbers', 'request_quote', 'account_balance_wallet', 'date_range',
  'list', 'warning', 'bug_report', 'database', 'link', 'alternate_email',
  'call', 'lan', 'key', 'draw', 'format_quote', 'percent',
  // interface
  'close', 'undo', 'add', 'delete', 'expand_more', 'check', 'folder',
  'grid_view', 'view_list', 'auto_awesome', 'photo_album', 'hub',
  'visibility_off', 'inventory_2', 'edit', 'more_horiz', 'search',
  'chevron_left', 'chevron_right', 'bookmark_add',
  // appearance
  'light_mode', 'dark_mode', 'brightness_auto',
];

async function pathFor(name: string): Promise<string> {
  const res = await fetch(SRC(name));
  if (!res.ok) throw new Error(`${name}: HTTP ${res.status}`);
  const svg = await res.text();
  // Every Material Symbol is a single <path> on a 0 -960 960 960 viewBox.
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (!paths.length) throw new Error(`${name}: no path data`);
  return paths.join(' ');
}

const entries: [string, string][] = [];
for (const name of MANIFEST) {
  entries.push([name, await pathFor(name)]);
  process.stdout.write('.');
}
process.stdout.write('\n');

const body = entries
  .map(([name, d]) => `  '${name}': '${d.replace(/'/g, "\'")}',`)
  .join('\n');

await writeFile(
  'lib/icons/paths.ts',
  `/* GENERATED by scripts/fetch-icons.mts -- do not edit by hand.
 *
 * Material Symbols, (c) Google, Apache License 2.0.
 * https://github.com/google/material-design-icons
 *
 * Every glyph is one path on a 0 -960 960 960 viewBox.
 */

export const ICON_PATHS: Record<string, string> = {
${body}
};

export type IconName = keyof typeof ICON_PATHS;
`,
  'utf8',
);

console.log(`wrote lib/icons/paths.ts (${entries.length} icons)`);
